// Generated by gencpp from file servicio_suma/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICIO_SUMA_MESSAGE_ADDTWOINTS_H
#define SERVICIO_SUMA_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <servicio_suma/AddTwoIntsRequest.h>
#include <servicio_suma/AddTwoIntsResponse.h>


namespace servicio_suma
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace servicio_suma


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servicio_suma::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::servicio_suma::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::servicio_suma::AddTwoInts > {
  static const char* value()
  {
    return "servicio_suma/AddTwoInts";
  }

  static const char* value(const ::servicio_suma::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::servicio_suma::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::servicio_suma::AddTwoInts >
template<>
struct MD5Sum< ::servicio_suma::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servicio_suma::AddTwoInts >::value();
  }
  static const char* value(const ::servicio_suma::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicio_suma::AddTwoIntsRequest> should match
// service_traits::DataType< ::servicio_suma::AddTwoInts >
template<>
struct DataType< ::servicio_suma::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::servicio_suma::AddTwoInts >::value();
  }
  static const char* value(const ::servicio_suma::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servicio_suma::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::servicio_suma::AddTwoInts >
template<>
struct MD5Sum< ::servicio_suma::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servicio_suma::AddTwoInts >::value();
  }
  static const char* value(const ::servicio_suma::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicio_suma::AddTwoIntsResponse> should match
// service_traits::DataType< ::servicio_suma::AddTwoInts >
template<>
struct DataType< ::servicio_suma::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::servicio_suma::AddTwoInts >::value();
  }
  static const char* value(const ::servicio_suma::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICIO_SUMA_MESSAGE_ADDTWOINTS_H
